{
  "kind":"youtube#searchListResponse",
  "etag":"\"F9iA7pnxqNgrkOutjQAa9F2k8HY/sp4fiTdtg5t9eugRHQeBO2IK-ew\"",
  "nextPageToken":"CAUQAA",
  "pageInfo":{
    "totalResults":80,
    "resultsPerPage":5
  },
  "items":[
    {
      "kind":"youtube#searchResult",
      "etag":"\"F9iA7pnxqNgrkOutjQAa9F2k8HY/uK3Y9XSHbJM3iHGHuJG5G97u7HI\"",
      "id":{
        "kind":"youtube#video",
        "videoId":"xwtdhWltSIg"
      },
      "snippet":{
        "publishedAt":"2011-07-02T00:22:34.000Z",
        "channelId":"UC7eaRqtonpyiYw0Pns0Au_g",
        "title":"R.E.M. - Losing My Religion (Video)",
        "description":"© 2006 WMG\r\nLosing My Religion (Video)\r\nGet Part Lies, Part Heart, Part Truth, Part Garbage: 1982- 2011, the definitive R.E.M. greatest hits collection coming 11/15/2011!\r\nAmazon: http://amzn.to/vBDlg5 iTunes: http://glnk.it/k8",
        "thumbnails":{
          "default":{
            "url":"https://i.ytimg.com/vi/xwtdhWltSIg/default.jpg"
          },
          "medium":{
            "url":"https://i.ytimg.com/vi/xwtdhWltSIg/mqdefault.jpg"
          },
          "high":{
            "url":"https://i.ytimg.com/vi/xwtdhWltSIg/hqdefault.jpg"
          }
        },
        "channelTitle":"remhq",
        "liveBroadcastContent":"none"
      }
    },
    {
      "kind":"youtube#searchResult",
      "etag":"\"F9iA7pnxqNgrkOutjQAa9F2k8HY/Hzu5DDt0QOsQ6KtMugvcxB8aHoQ\"",
      "id":{
        "kind":"youtube#video",
        "videoId":"YYOKMUTTDdA"
      },
      "snippet":{
        "publishedAt":"2009-10-27T02:21:29.000Z",
        "channelId":"UC7eaRqtonpyiYw0Pns0Au_g",
        "title":"R.E.M. - Shiny Happy People (Video)",
        "description":"© 2005 WMG\r\nShiny Happy People (Video)\r\n\r\nGet Part Lies, Part Heart, Part Truth, Part Garbage: 1982- 2011, the definitive R.E.M. greatest hits collection coming 11/15/2011!\r\nAmazon: http://amzn.to/vBDlg5 iTunes: http://glnk.it/k8",
        "thumbnails":{
          "default":{
            "url":"https://i.ytimg.com/vi/YYOKMUTTDdA/default.jpg"
          },
          "medium":{
            "url":"https://i.ytimg.com/vi/YYOKMUTTDdA/mqdefault.jpg"
          },
          "high":{
            "url":"https://i.ytimg.com/vi/YYOKMUTTDdA/hqdefault.jpg"
          }
        },
        "channelTitle":"remhq",
        "liveBroadcastContent":"none"
      }
    },
    {
      "kind":"youtube#searchResult",
      "etag":"\"F9iA7pnxqNgrkOutjQAa9F2k8HY/5wNQvo-9H2XIHBOqdwV2m2WjOmg\"",
      "id":{
        "kind":"youtube#video",
        "videoId":"oC7er_6dpsI"
      },
      "snippet":{
        "publishedAt":"2009-10-27T02:21:29.000Z",
        "channelId":"UC7eaRqtonpyiYw0Pns0Au_g",
        "title":"R.E.M. - \"Near Wild Heaven\" ( This Film Is On Version)",
        "description":"© 2006 WMG\nNear Wild Heaven ( Film Is On Video Version )",
        "thumbnails":{
          "default":{
            "url":"https://i.ytimg.com/vi/oC7er_6dpsI/default.jpg"
          },
          "medium":{
            "url":"https://i.ytimg.com/vi/oC7er_6dpsI/mqdefault.jpg"
          },
          "high":{
            "url":"https://i.ytimg.com/vi/oC7er_6dpsI/hqdefault.jpg"
          }
        },
        "channelTitle":"remhq",
        "liveBroadcastContent":"none"
      }
    },
    {
      "kind":"youtube#searchResult",
      "etag":"\"F9iA7pnxqNgrkOutjQAa9F2k8HY/obHT0w_c0R70Nzo6qeiTd2SH-JM\"",
      "id":{
        "kind":"youtube#video",
        "videoId":"-R2hvKDFLHE"
      },
      "snippet":{
        "publishedAt":"2009-10-27T02:21:29.000Z",
        "channelId":"UC7eaRqtonpyiYw0Pns0Au_g",
        "title":"R.E.M. - Bittersweet Me (Video)",
        "description":"© 2007 WMG\nBittersweet Me (Video)",
        "thumbnails":{
          "default":{
            "url":"https://i.ytimg.com/vi/-R2hvKDFLHE/default.jpg"
          },
          "medium":{
            "url":"https://i.ytimg.com/vi/-R2hvKDFLHE/mqdefault.jpg"
          },
          "high":{
            "url":"https://i.ytimg.com/vi/-R2hvKDFLHE/hqdefault.jpg"
          }
        },
        "channelTitle":"remhq",
        "liveBroadcastContent":"none"
      }
    },
    {
      "kind":"youtube#searchResult",
      "etag":"\"F9iA7pnxqNgrkOutjQAa9F2k8HY/8-RulTnZxLBch4mJvEsVpEQW3b0\"",
      "id":{
        "kind":"youtube#video",
        "videoId":"Qt2mbGP6vFI"
      },
      "snippet":{
        "publishedAt":"2010-05-10T13:41:57.000Z",
        "channelId":"UC4JeRiQvPQ_nb1BZWjk9QoA",
        "title":"Phil Collins - Another Day In Paradise",
        "description":"THE NEW ALBUM IS NOW AVAILABLE ON iTUNES: http://www.smarturl.it/goingback\r\n\r\n© 2007 WMG\r\nAnother Day In Paradise\r\n\r\nOfficial Website:\r\nhttp://www.philcollins.com\r\n\r\nOfficial Facebook:\r\nhttp://www.facebook.com/philcollins\r\n\r\nOfficial Twitter:\r\nhttp://www.twitter.com/PhilCollinsFeed\r\n\r\nOfficial MySpace:\r\nhttp://www.myspace.com/philcollins",
        "thumbnails":{
          "default":{
            "url":"https://i.ytimg.com/vi/Qt2mbGP6vFI/default.jpg"
          },
          "medium":{
            "url":"https://i.ytimg.com/vi/Qt2mbGP6vFI/mqdefault.jpg"
          },
          "high":{
            "url":"https://i.ytimg.com/vi/Qt2mbGP6vFI/hqdefault.jpg"
          }
        },
        "channelTitle":"philcollins",
        "liveBroadcastContent":"none"
      }
    }
  ]
}